site_name: GPT ALL STAR
site_author: kyaukyuai
site_description: AI-powered code generation tool for scratch development of web applications with a team collaboration of autonomous AI agents. This is a research-project, and its primary value is to explore the possibility of autonomous AI agents.
repo_name: gpt-all-star
repo_url: https://github.com/kyaukyuai/gpt-all-star

theme:
  name: material
  language: en
